version: '2.1'
services:
  django:
    image: appbackend:0.1
    build:
      context: ./config/django-image
    volumes:
      - ./src/django/:/usr/src/app:delegated
    environment:
      DEBUG: ${DEBUG}
      PROD: ${PROD}
      DB_HOST: ${DATABASE_HOST}
      DB_NAME: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASS}
      DJANGO_SU_NAME: ${DJANGO_SU_ADMIN}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      DJANGO_ADMIN_PATH: ${DJANGO_ADMIN_PATH}
    ports:
      - 8000:8000
    networks:
      red:
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    command: postgres -c 'max_connections=600'
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data:delegated
    networks:
      red:

networks:
  red:
