# Generated by Django 5.0.2 on 2024-02-06 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='expedientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_expediente', models.IntegerField()),
                ('nro_pago', models.IntegerField()),
                ('detalles', models.CharField()),
                ('año', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpediAPI.proveedor')),
            ],
        ),
    ]
