# Generated by Django 5.0.2 on 2024-02-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpediAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientes',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
